import React from 'react';
import './App.css';
import Locations from './components/Locations'
import {Container} from 'reactstrap'
import DetailsPage from './components/DetailsPage'
import AddRestaurant from './components/AddRestaurant'
import axios from 'axios'
import Navbar from './components/NavBar'
import {
  BrowserRouter as Router,
  Switch,
  Route
} from "react-router-dom";


var BASEURL = '13v4yjfvyi.execute-api.us-east-1.amazonaws.com';
class App extends React.Component {
  constructor(props){
    super(props)
    this.state = {list: [], details: {}, homePageLoaded: false, error: false}
    this.renderDetails = this.renderDetails.bind(this);
  }
async componentDidMount(){
  
  this.setState({homePageLoaded:true, list: [
    {
        "restaurant": "Amoos Restaurant",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "6271 Old Dominion Dr, McLean, VA 22101",
        "reviews": [],
        "url": "https://www.amoosrestaurant.com/",
        "cuisine": "Persian",
        "restaurantid": "854ea214-3cf0-4d6a-882b-49ad5f38fc18",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 448-8500",
        "type": "Semi-Formal"
    },
    {
        "restaurant": "New Yorker Pizza",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "828 S King St, Leesburg, VA 20175",
        "reviews": [],
        "url": "https://slicelife.com/restaurants/va/leesburg/20175/new-yorker-pizza/menu?utm_source=gmb_menu",
        "cuisine": "American",
        "restaurantid": "4e8d9e70-735a-4dba-82e0-598903919d3d",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 777-6985",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Spice 6",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "Multiple Locations across DMV",
        "reviews": [],
        "url": "https://www.spice-6.com/",
        "cuisine": "Indian",
        "restaurantid": "d74e9c7b-c92a-4c7a-9bc6-b39a01680c10",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Gyro Factory",
        "zip": "22079",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "2858, 8222 Gunston Corner Ln",
        "reviews": [],
        "url": "https://gyrofactoryva.com/",
        "cuisine": "Fast Food",
        "restaurantid": "ed3985c4-d722-45f6-8046-322872defa9f",
        "state": "VA",
        "city": "Lorton",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 495-9777",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Perfect Pollo",
        "zip": "",
        "rating": "5.0",
        "handMachineSlaughtered": "",
        "address": "11503 Tidewater Trail, Fredericksburg, VA 22408",
        "reviews": [
            {
                "rating": "5",
                "createdAt": "2/1/2022, 7:38:57 PM",
                "comment": "",
                "approved": true,
                "restaurantid": "4bd12d3a-213d-4806-95b1-3ff5d850fb08"
            }
        ],
        "url": "https://perfectpollo.com/",
        "cuisine": "Peruvian",
        "restaurantid": "4bd12d3a-213d-4806-95b1-3ff5d850fb08",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Virginia",
        "halalStatus": "",
        "phone": "(540) 371-6900",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Red Kabob",
        "zip": "",
        "rating": "5.0",
        "handMachineSlaughtered": "",
        "address": "521-A E Market St, Leesburg, VA 20176",
        "reviews": [
            {
                "rating": "5",
                "createdAt": "2/1/2022, 8:26:13 PM",
                "comment": "I love red kabob",
                "approved": true,
                "restaurantid": "2b1becea-2132-47e9-a804-39575f47e0ea"
            }
        ],
        "url": "https://red-kabob.com/",
        "cuisine": "Afghan",
        "restaurantid": "2b1becea-2132-47e9-a804-39575f47e0ea",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 777-5277",
        "type": ""
    },
    {
        "restaurant": "Kabob Corner",
        "zip": "22030",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "10893 Main St",
        "reviews": [],
        "url": "https://www.kabobcornerfairfax.com/",
        "cuisine": "Afghan",
        "restaurantid": "9f912c46-398b-4edd-9afa-34d753b52349",
        "state": "VA",
        "city": "Fairfax",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Ottoman Kitchen",
        "zip": "20151",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "4300 Chantilly Shopping Center #1n",
        "reviews": [],
        "url": "https://ottomankitchen.us/",
        "cuisine": "Turkish",
        "restaurantid": "f2a0795d-0c83-478e-b7c3-210a6af491af",
        "state": "VA",
        "city": "Chantilly",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(571) 287-7278",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Frito Chicken",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "44650 Waxpool Rd #100, Ashburn, VA 20147",
        "reviews": [],
        "url": "http://fritochicken.com/menu.php",
        "cuisine": "American",
        "restaurantid": "54d7a241-aca9-489f-9cdb-fcb719c6c011",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Virginia",
        "halalStatus": "",
        "phone": "",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Bawadi",
        "zip": "",
        "rating": "4.5",
        "handMachineSlaughtered": "",
        "address": "6304 Leesburg Pike, Falls Church, VA 22044",
        "reviews": [
            {
                "rating": "5",
                "createdAt": "1/31/2022, 6:19:24 PM",
                "comment": "",
                "approved": true,
                "restaurantid": "af536f4a-972e-464c-aac7-50a8a824c555"
            },
            {
                "rating": "4",
                "createdAt": "1/31/2022, 11:15:43 PM",
                "comment": "",
                "approved": true,
                "restaurantid": "af536f4a-972e-464c-aac7-50a8a824c555"
            }
        ],
        "url": "http://www.bawadiva.com/",
        "cuisine": "Mediterranean",
        "restaurantid": "af536f4a-972e-464c-aac7-50a8a824c555",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 845-1600",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Punjabi by Nature",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "Leesburg/Chantilly/Vienna",
        "reviews": [],
        "url": "https://www.punjabibynature.us/",
        "cuisine": "Indian",
        "restaurantid": "f4c36104-e7e6-4fcf-9cdf-2a97943beecd",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Flavour Pastry",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "3821 C S George Mason Dr, Falls Church, VA 22041",
        "reviews": [],
        "url": "http://flavorpastry.com/",
        "cuisine": "Bakery",
        "restaurantid": "98205dba-8ced-4eb3-93bf-b0aa00b791e0",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 998-0040",
        "type": ""
    },
    {
        "restaurant": "Sakina Halal Grill",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "1108 K St NW, Washington, DC 20005",
        "reviews": [],
        "url": "http://www.sakinahalalgrill.com/",
        "cuisine": "Pakistani",
        "restaurantid": "7d0ce464-dc42-4799-aa18-c58f4b53e482",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Washington DC",
        "halalStatus": "",
        "phone": "(202) 637-9770",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Anatolian Bistro",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "13029 Worldgate Dr, Herndon, VA 20170",
        "reviews": [],
        "url": "https://anatolianbistro.com/",
        "cuisine": "Turkish",
        "restaurantid": "eccef43b-13d9-4d5e-8570-fe8bc85541fd",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 481-8080",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Taste of Lebanon",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "510 E Market St Unit F, Leesburg, VA 20176",
        "reviews": [],
        "url": "http://www.tasteoflebanon.net/",
        "cuisine": "Mediterranean",
        "restaurantid": "8f960ba4-ced7-4b6f-97c0-2abf98bf3676",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(571) 707-8847",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Mr. Chicken",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "7077 Brookfield Plaza, Springfield, VA 22150",
        "reviews": [],
        "url": "http://www.mrchicken.site/?utm_source=google&utm_medium=website&utm_campaign=Mr%20Chicken&utm_term=6144de0544dc6d000169d34a",
        "cuisine": "Fast Food",
        "restaurantid": "6eaf9605-963b-4583-9111-ef40548b468f",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 866-3003",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Amina Thai",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "8624 Colesville Rd, Silver Spring, MD 20910",
        "reviews": [],
        "url": "http://aminathai-silverspring.square.site/",
        "cuisine": "Thai",
        "restaurantid": "bea363ca-a0ea-4920-9ac3-145aa7e985b7",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Maryland",
        "halalStatus": "",
        "phone": "(301) 588-3588",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Elevation Burger",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "VA/MD/DC **NOT ALL LOCATIONS HAVE HALAL BACON**",
        "reviews": [],
        "url": "http://elevationburger.com/",
        "cuisine": "American",
        "restaurantid": "8082912a-9179-46a8-8afb-75bf553345b0",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Lasani",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "8998-B Lorton Station Blvd, Lorton, VA 22079",
        "reviews": [],
        "url": "https://www.ritual.co/order/lasani-kabob-restaurant-8998-lorton-station-blvd-lorton-va-22079-usa-lorton/ef5a",
        "cuisine": "Pakistani",
        "restaurantid": "04d0b89f-9873-4eb0-a700-2e3e45e20383",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 372-2980",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Mr. Pollo",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "23520 Overland Dr #152, Sterling, VA 20166",
        "reviews": [],
        "cuisine": "Peruvian",
        "restaurantid": "41b695fd-43db-4f37-a5ce-220cb5474c19",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 996-2456",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Khan Kabob",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "4229 Lafayette Center Dr #1475, Chantilly, VA 20151",
        "reviews": [],
        "url": "http://www.khankabob.com/",
        "cuisine": "Pakistani",
        "restaurantid": "4ff32e47-3cc8-4c3b-be29-2165ff025d75",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 817-1200",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Aditi Indian Dining",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "5926 Kingstowne Blvd #150, Alexandria, VA 22315",
        "reviews": [],
        "url": "http://myaditi.com/",
        "cuisine": "Indian",
        "restaurantid": "668b4da8-9f62-41ab-8ab4-bde07b14f917",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 922-6111",
        "type": "Formal"
    },
    {
        "restaurant": "Kabob Corner of Stafford",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "1515 Stafford Market Pl #105, Stafford, VA 22554",
        "reviews": [],
        "url": "http://www.kabobcornerstafford.com/",
        "cuisine": "Afghan",
        "restaurantid": "f4bc7a62-bcc4-43e1-8e69-8a78c485449a",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Virginia",
        "halalStatus": "",
        "phone": "(540) 288-8008",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Hyderbad Palace",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "46970 Community Plaza, Sterling, VA 20164",
        "reviews": [],
        "url": "https://hyderabadpalace504.wixsite.com/home",
        "cuisine": "Pakistani",
        "restaurantid": "abbb59e0-a8a7-4eab-9ff4-3a31f81ef0e8",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 444-0381",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Flame Kabob",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "Springfield/Fairfax/Leesburg",
        "reviews": [],
        "url": "https://www.flame-kabob.com/order-food-online/all/",
        "cuisine": "Afghan",
        "restaurantid": "d555ae15-6a77-4e5c-a5d8-354d44d99c5f",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "",
        "type": ""
    },
    {
        "restaurant": "Shamshiry",
        "zip": "22182",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "8607 Westwood Center Dr",
        "reviews": [],
        "url": "http://www.shamshiry.com/",
        "cuisine": "Afghan",
        "restaurantid": "e773d014-9fec-4f9e-a072-7ab176e1fd1d",
        "state": "VA",
        "city": "Vienna",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 448-8883",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Sapphire",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "8201 Greensboro Dr #109, Tysons, VA 22102",
        "reviews": [],
        "url": "http://www.sapphiretysons.com/",
        "cuisine": "Pakistani",
        "restaurantid": "767b9bb4-4a69-4646-8491-a459e9e06825",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 288-3232",
        "type": "Formal"
    },
    {
        "restaurant": "Legends Chicken & Grill",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "6401 Annapolis Rd, Hyattsville, MD 20784",
        "reviews": [],
        "cuisine": "American",
        "restaurantid": "10bc56a4-cbc2-441c-83a4-081b3c038dea",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Maryland",
        "halalStatus": "",
        "phone": "(240) 770-5151",
        "type": ""
    },
    {
        "restaurant": "Niralla",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "7038 Spring Garden Dr, Springfield, VA 22150",
        "reviews": [],
        "url": "http://nirallasweets.com/",
        "cuisine": "Pakistani",
        "restaurantid": "9fbbd7cb-67b9-4dc9-ac13-e058570fe42e",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 923-9460",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Hunan Village",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "42920 Piccadilly Plaza Unit#131, Ashburn, VA 20147",
        "reviews": [],
        "url": "https://www.huvill.com/",
        "cuisine": "Chinese",
        "restaurantid": "6e690a61-c8e9-4e9a-9655-4c4ba5876fdb",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 726-9321",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Darya Kabob",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "21800 Towncenter Plaza #264, Sterling, VA 20164",
        "reviews": [],
        "url": "http://www.daryakabob.com/",
        "cuisine": "Afghan",
        "restaurantid": "a4007a1f-6ec1-46b6-a8ec-47de6809a94e",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 404-4443",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Raouche Cafe",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "2839 Gallows Rd, Falls Church, VA 22042",
        "reviews": [],
        "url": "http://www.raouchecafe.com/",
        "cuisine": "Middle Eastern",
        "restaurantid": "6a2546d4-5e0c-4d18-a923-e8783e8b354b",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "Confirmed by management",
        "phone": "(703) 205-9099",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Namaste",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "6138 Rose Hill Dr, Alexandria, VA 22310",
        "reviews": [],
        "url": "http://namasteva.com/",
        "cuisine": "Nepalese",
        "restaurantid": "c01ed658-5a44-4d57-ba3b-24402d896b49",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 822-0408",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Cafe Rice and Kabob",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "47100 Community Plaza # 114, Sterling, VA 20164",
        "reviews": [],
        "url": "http://www.cafericekabob.com/?utm_source=gmb&utm_medium=website",
        "cuisine": "Afghan",
        "restaurantid": "6474835a-11e3-41dc-86b4-9c0eed97c2f8",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 444-2690",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Kabul Kabob Express",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "514-A S Van Dorn St, Alexandria, VA 22304",
        "reviews": [],
        "cuisine": "Afghan",
        "restaurantid": "165ae3f7-aa9c-4c5a-b929-7e004d4ab2d6",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 751-1833",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Shiney's Sweets and restaurant",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "4231 MARKHAM ST - D, Annandale, VA 22003",
        "reviews": [],
        "url": "http://www.shineysrestaurant.com/aboutus.html#",
        "cuisine": "Pakistani",
        "restaurantid": "3632fe93-014d-4141-b4ed-29e0d2d87b4a",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 642-0460",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Eerkins",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "4008 University Dr, Fairfax, VA 22030",
        "reviews": [],
        "url": "http://www.eerkins.com/",
        "cuisine": "Chinese",
        "restaurantid": "e3621844-56f1-442d-ac0e-43f5ffcefb3e",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 352-1121",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Mandarin Chinese Halal Restaurant",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "6366 Commerce St, Springfield, VA 22150",
        "reviews": [],
        "url": "https://www.mandarinchinese-halal.com/",
        "cuisine": "Chinese",
        "restaurantid": "9b067744-3273-44ce-a884-7e33381afe67",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Virginia",
        "halalStatus": "",
        "phone": "(703) 912-3118",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Halal Guys",
        "zip": "",
        "rating": "5.0",
        "handMachineSlaughtered": "",
        "address": "Multiple Locations across DMV",
        "reviews": [
            {
                "rating": "5",
                "createdAt": "1/31/2022, 8:37:57 PM",
                "comment": "This place is fire!",
                "approved": true,
                "restaurantid": "8d5f4285-587b-4f66-8752-9ee704be389c"
            }
        ],
        "url": "https://thehalalguys.com/locations/10625-braddock-rd-fairfax/",
        "cuisine": "Fast Food",
        "restaurantid": "8d5f4285-587b-4f66-8752-9ee704be389c",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "Confirmed by management",
        "phone": "",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Two Brothers Chicken",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "14845 Build America Dr, Woodbridge, VA 22191",
        "reviews": [],
        "url": "http://www.twobrotherschicken.com/",
        "cuisine": "Fast Food",
        "restaurantid": "4228a797-2a93-4ba9-9544-5b7f29374a74",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(571) 384-6675",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Cheesesteak Express & Kabob Depot",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "24651 Southpoint Dr, Chantilly, VA 20152",
        "reviews": [],
        "cuisine": "American",
        "restaurantid": "fd66792a-3c6f-455c-9256-4ec43d0fdbf1",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 957-4705",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Kabobroom",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "2777 Patriot Hwy, Stafford, VA 22554",
        "reviews": [],
        "url": "http://kabobroom.com/",
        "cuisine": "Afghan",
        "restaurantid": "4e7e1fb4-47b7-489e-9f27-a8f1a52b60f1",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Virginia",
        "halalStatus": "",
        "phone": "(540) 288-4400",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Kiroran",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "10728 Fairfax Blvd, Fairfax, VA 22030",
        "reviews": [],
        "url": "https://kiroranusava.com/",
        "cuisine": "Chinese",
        "restaurantid": "f342d156-b51a-41be-b2b7-326c0a2e5c89",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 865-5033",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Aroma Pizza",
        "zip": "22079",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "7200 J Telegraph Square Drive",
        "reviews": [],
        "url": "https://www.aromapizzacompanymenu.com/",
        "cuisine": "Fast Food",
        "restaurantid": "346de457-b554-4a2a-a734-c00cfd2e5914",
        "state": "VA",
        "city": "Lorton",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "Confirmed by management, halal sign in/outside restaurant",
        "phone": "(703) 541-3030",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Dunya Banquet Hall & Restaurant",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "5951 Stevenson Ave, Alexandria, VA 22304",
        "reviews": [],
        "url": "http://www.dunyabanquet.com/",
        "cuisine": "Afghan",
        "restaurantid": "dd89d9a1-f495-488b-a826-bdb87cb0c111",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 212-8511",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Nick's Taverna",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "42395 Ryan Rd, Ashburn, VA 20148",
        "reviews": [],
        "url": "https://nickstaverna.com/",
        "cuisine": "Mediterranean",
        "restaurantid": "346a8c4c-fa1c-47d4-95f0-c64dd2d7df0f",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Virginia",
        "halalStatus": "",
        "phone": "(703) 327-7844",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Kabob and Curry House",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "2913 Arlington Dr A, Alexandria, VA 22306",
        "reviews": [],
        "url": "http://kabobncurryva.us/",
        "cuisine": "Pakistani",
        "restaurantid": "16cf79b2-8b0d-46cf-8ee2-74b395715fca",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 768-4100",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Moby Dick",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "VA/MD/DC",
        "reviews": [],
        "url": "https://www.mobyskabob.com/",
        "cuisine": "Persian",
        "restaurantid": "7e36ca6b-ba24-4548-ac2e-f623239f13df",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Tandoori Village Dhawat",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "7607 Centreville Rd, Manassas, VA 20111",
        "reviews": [],
        "cuisine": "Pakistani",
        "restaurantid": "63e00643-ecb2-4e91-a51c-61408b713311",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 369-6526",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Peri Peri Original",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "6456 Old Beulah St, Alexandria, VA 22315",
        "reviews": [],
        "url": "https://periperioriginaldmv.com/",
        "cuisine": "Portuguese",
        "restaurantid": "a474f259-9336-4f6d-89cf-1700c301c891",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 337-2399",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Jerusalem",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "3405 Payne St, Falls Church, VA 22041",
        "reviews": [],
        "url": "https://www.jerusalem-va.net/",
        "cuisine": "Palestinian/Mediterranean",
        "restaurantid": "7287476b-7dd1-42e0-af4f-c762bf20587a",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 379-4200",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Burger 7",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "Alexandria/Arlington/Falls Church/Vienna",
        "reviews": [],
        "url": "http://burgerseven.com/",
        "cuisine": "American",
        "restaurantid": "1bad617d-c095-4223-b41b-0b56ede64efa",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Coco Rico",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "5655 General Washington Dr Suite A, Alexandria, VA 22312",
        "reviews": [],
        "url": "http://www.cocoricochicken.com/",
        "cuisine": "Peruvian",
        "restaurantid": "2a99b759-7f11-4109-b826-72ff47c67b4c",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 822-0124",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Lebanese Kitchen",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "13031 Lee Jackson Memorial Hwy, Fairfax, VA 22033",
        "reviews": [],
        "url": "https://www.lebanesekitchenmenu.com/",
        "cuisine": "Lebanese/Mediterranean",
        "restaurantid": "adb3f01b-5f1b-45e1-b0ef-713d0d14f3b4",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 378-5001",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Maiwand Kabob",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "Multiple Locations across DC and Maryland",
        "reviews": [],
        "url": "https://maiwandkabob.com/",
        "cuisine": "Afghan",
        "restaurantid": "fbe720db-d6ce-42a5-b73e-63ba751fb272",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Maryland",
        "halalStatus": "",
        "phone": "",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Kabob & Chicken",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "45591 Dulles Eastern Plaza #198, Sterling, VA 20166",
        "reviews": [],
        "url": "http://www.kabobandchicken.com/",
        "cuisine": "Indian",
        "restaurantid": "3b9a0b0b-5c08-49ad-93a6-3466f1fd3c38",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 421-0786",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Ravi Kabob",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "305 N Glebe Rd, Arlington, VA 22203",
        "reviews": [],
        "url": "https://menupages.com/ravi-kabob-house/305-n-glebe-rd-arlington",
        "cuisine": "Pakistani",
        "restaurantid": "c7fc859a-8f08-44ce-83b5-8161569805c9",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 522-6666",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Haifa Grill",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "3541 Carlin Springs Rd, Falls Church, VA 22041",
        "reviews": [],
        "url": "http://haifagrill.com/",
        "cuisine": "Palestinian/Mediterranean",
        "restaurantid": "4ac2d764-5a44-44fe-9a8a-207eb0013238",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 820-4243",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Tempo Restaurant",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "1195 20th St NW, Washington, DC 20036",
        "reviews": [],
        "url": "http://www.temporestaurant.com/",
        "cuisine": "Turkish",
        "restaurantid": "e7ca6d93-d38d-48d9-af31-07388fcd4b6a",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Washington DC",
        "halalStatus": "",
        "phone": "",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Pizza & Gyro",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "7058 Spring Garden Dr, Springfield, VA 22150",
        "reviews": [],
        "url": "https://www.mypizzaandgyro.com/",
        "cuisine": "American",
        "restaurantid": "2bdcc4af-58e9-4d57-99a8-fbb2f6e92853",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Virginia",
        "halalStatus": "",
        "phone": "(703) 913-5500",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Toosso",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "1596 Rockville Pike A, Rockville, MD 20852",
        "reviews": [],
        "url": "http://www.toosso.com/",
        "cuisine": "Pakistani",
        "restaurantid": "9e209088-b3cd-421d-bad0-682d450db4df",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Maryland",
        "halalStatus": "",
        "phone": "(301) 768-4645",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Danish Foods",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "1722 N Rolling Rd, Windsor Mill, MD 21244",
        "reviews": [],
        "cuisine": "Danish",
        "restaurantid": "5c4fe9a4-ef4c-449b-a4fb-8c9b84f5f9ea",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Maryland",
        "halalStatus": "",
        "phone": "(410) 298-0960",
        "type": "Quick Bite"
    },
    {
        "restaurant": "New Yorker Pizza",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "828 S King St, Leesburg, VA 20175",
        "reviews": [],
        "url": "http://newyorkerpizzamenu.com/",
        "cuisine": "American/Pizza",
        "restaurantid": "c8f28e94-2d82-4b80-a0e4-a9efdf47ae6e",
        "state": "VA",
        "city": "Vienna",
        "region": "Northern Virginia",
        "phone": "(703) 777-6985",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Cherry Blossom Afghan Restaurant",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "46110 Lake Center Plaza, Sterling, VA 20165",
        "reviews": [],
        "url": "http://www.cherryblossomhall.com/",
        "cuisine": "Afghan",
        "restaurantid": "ce3fb19a-0cd4-4dbf-9937-7d78d483bf9d",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 444-0080",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Fattoush",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "1109 W Broad St, Falls Church, VA 22046",
        "reviews": [],
        "url": "http://www.fettoosh.com/",
        "cuisine": "Moroccan/Lebanese",
        "restaurantid": "633862fd-9ea6-4317-8ae9-3bd6684e90ce",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 534-0708",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Jenin Pastry",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "5820 Seminary Rd A, Falls Church, VA 22041",
        "reviews": [],
        "url": "http://jeninpastry.com/",
        "cuisine": "Palestinian/Mediterranean",
        "restaurantid": "a59ee737-f461-4ed4-9ccf-839fb96e8dec",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 820-0100",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Perfect Pitas",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "2200 Clarendon Blvd #7, Arlington, VA 22201",
        "reviews": [],
        "url": "http://www.theperfectpita.com/",
        "cuisine": "Mediternean",
        "restaurantid": "1b1ae0f1-b08a-4c19-adf7-c14a5a6d7f0c",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 527-1511",
        "type": "Family/Casual"
    },
    {
        "restaurant": "BBQ Tonight",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "45965 Regal Plaza, Sterling, VA 20165",
        "reviews": [],
        "cuisine": "Pakistani/Afghan",
        "restaurantid": "7f864657-272d-4db9-a548-7a78fcc11cf3",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(202) 213-4797",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Kabob Palace",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "2315 S Eads St, Arlington, VA 22202",
        "reviews": [],
        "url": "http://www.kabobpalaceusa.com/",
        "cuisine": "Pakistani",
        "restaurantid": "5d55e27e-d3f8-4f88-8bc7-d6c851dd2608",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 486-3535",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Bamian",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "5634 Leesburg Pike, Falls Church, VA 22041",
        "reviews": [],
        "url": "http://www.bamianafghancuisine.com/?utm_source=gmb&utm_medium=website",
        "cuisine": "Afghan",
        "restaurantid": "022f7b8a-6fca-409a-a2d2-b4d264e90e74",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 820-7880",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Muncheez",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "1071 Wisconsin Ave NW, Washington, DC 20007",
        "reviews": [],
        "url": "https://muncheezdc.com/",
        "cuisine": "Mediterranean",
        "restaurantid": "c5db179d-3358-4590-af3b-b2d66aa64089",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "District of Columbia",
        "halalStatus": "",
        "phone": "(202) 567-3000",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Bombay Tandoor",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "8603 Westwood Center Dr, Vienna, VA 22182",
        "reviews": [],
        "url": "http://www.bombaytandoorvienna.com/?utm_source=gmb&utm_medium=website",
        "cuisine": "Indian",
        "restaurantid": "ac8bdf7e-7b73-4ea0-a55c-99ca7c74c51e",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 734-2202",
        "type": "Formal"
    },
    {
        "restaurant": "Lal Qila Restaurant",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "6901 Security Blvd, Windsor Mill, MD 21244",
        "reviews": [],
        "url": "https://www.mealhi5.com/Azan-Karahi-And-Kabab/",
        "cuisine": "Pakistani",
        "restaurantid": "f1003ab4-7a9b-4099-bec7-de85dffaec43",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Maryland",
        "halalStatus": "",
        "phone": "(410) 265-1088",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Earls Kitchen + Bar",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "7902 Tysons One Pl, Tysons, VA 22102",
        "reviews": [],
        "url": "https://earls.ca/locations/tysons-corner",
        "cuisine": "American",
        "restaurantid": "811b2a64-f964-4fc1-98df-4021f8cc0564",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Virginia",
        "halalStatus": "",
        "phone": "(703) 847-1870",
        "type": "Formal"
    },
    {
        "restaurant": "Dera",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "7030 Spring Garden Dr, Springfield, VA 22150",
        "reviews": [],
        "url": "https://dera-restaurant.com/",
        "cuisine": "Pakistani",
        "restaurantid": "9406f194-2b21-4d84-a17e-aec609295b33",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 866-2233",
        "type": "Family/Casual"
    },
    {
        "restaurant": "Grill Kabob",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "8300 Sudley Rd, Manassas, VA 2010 (Mall)",
        "reviews": [],
        "url": "http://www.grillkabobrestaurants.com/",
        "cuisine": "Afghan",
        "restaurantid": "e9e09af9-09ab-4337-b805-cd7d24a611aa",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 330-7070",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Mezeh Mediterranean Grill",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "Multiple Locations across DMV",
        "reviews": [],
        "url": "http://www.mezeh.com/",
        "cuisine": "Middle Eastern",
        "restaurantid": "d54ca800-3324-4357-9a95-dd434fea3219",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "Confirmed by management",
        "phone": "",
        "type": "Quick Bite"
    },
    {
        "restaurant": "Mehran",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "23070 Oakgrove Rd, Sterling, VA 20166",
        "reviews": [],
        "url": "http://www.mehrankabob.com/",
        "cuisine": "Pakistani",
        "restaurantid": "4a729df1-2a7b-48c1-a03d-7b66caec87a1",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Northern Virginia",
        "halalStatus": "",
        "phone": "(703) 787-8888",
        "type": "Family/Casual"
    },
    {
        "restaurant": "China Taste",
        "zip": "",
        "rating": "0",
        "handMachineSlaughtered": "",
        "address": "20630 Ashburn Rd, Ashburn, VA 20147",
        "reviews": [],
        "url": "https://chinatastevatogo.com/",
        "cuisine": "Chinease",
        "restaurantid": "99f76659-1708-4ee8-8e4b-342799a3f847",
        "state": "",
        "city": "",
        "fullPartHalal": "",
        "special": "",
        "openUntil": "",
        "region": "Virginia",
        "halalStatus": "",
        "phone": "(703) 723-4834",
        "type": "Family/Casual"
    }
]})
  // axios.get(`https://${BASEURL}/restaurant`).then(data=>{
  //   let approvedRestaurants = data.data.filter(restaurant=>{
  //     this.setState({homePageLoaded: true})
  //     return restaurant
  //   })

  //   this.setState({list: approvedRestaurants})
  // }
  // ).catch(err=>{
  //   this.setState({homePageLoaded: true, error: true})
  //   console.log(err)
  // })
}

filterName = (query)=>{
  let filteredRestaurants = this.state.list;
  filteredRestaurants = filteredRestaurants.filter(restaurant =>{
    return restaurant.restaurant.toLowerCase().includes(query.toLowerCase())
  })
  this.setState({filteredRestaurants: filteredRestaurants})
}

filterCuisine = (query)=>{
  let filteredRestaurants = this.state.list;
  if (query === "All Cuisines"){
    this.setState({filteredRestaurants: this.state.list})
  }else{
      filteredRestaurants = filteredRestaurants.filter(restaurant =>{
        return restaurant.cuisine.toLowerCase().includes(query.toLowerCase())
      })
      this.setState({filteredRestaurants: filteredRestaurants})
  }
}

handleClick = (data) =>{
  this.setState({details: data, filteredRestaurants: this.state.list})
}

renderLocations = ()=>{
  return <Locations state={this.state} handleClick={this.handleClick} filterName={this.filterName} filterCuisine={this.filterCuisine}/>
}

renderDetails = (match)=>{
  return <DetailsPage details={this.state.details} match={match.match.params.id}/>
}
search(value, nameKey, myArray){
  for (var i=0; i < myArray.length; i++) {
      if (myArray[i][nameKey] === value) {
        return myArray[i];
      }
  }
}

renderAddRestaurant = ()=>{
  return <AddRestaurant/>
}
  render() 
    {    
      return(
       <div className="App">
         <Router > 
           <Navbar props={this.search}/>
           {/* <Link to="/restaurants" style={{textDecoration: 'none'}}><Header/></Link> */}
            <Container>
             <div>
                <Switch>
                  <Route exact path="/details/:id" component={this.renderDetails}/>
                  <Route path='/addRestaurant' component={this.renderAddRestaurant}/>
                  <Route path="/restaurants" component={this.renderLocations}/>
                  <Route path="/" component={this.renderLocations}/>
                </Switch>
              </div>
            </Container>
         </Router> 
       </div>)
    }
}

export default App;
